GET http://localhost:3000/api/test

###
# 2. get all routes
###
GET http://localhost:3000/routes

###
# 3. get route by id
###
GET http://localhost:3000/routes/64e79a6c7e35362ed995a062

###
# 4. create route
###
POST http://localhost:3000/routes
Content-Type: application/json

{
  "name": "route 2",
  "source_id": "ChIJUasLOhSPpgARevNCEqmwzbo",
  "destination_id": "ChIJD9TtBN-RpgARZxOFGySjO4Q"
}

##
# places
##

### Pegar o place_id
GET http://localhost:3000/places?text=rua alice marques, 260

### Pegar direções entre dois pontos
GET http://localhost:3000/directions?originId=ChIJUasLOhSPpgARevNCEqmwzbo&destinationId=ChIJFaMK2shZzpQRanfJ8jGUn9U